name = "Giac"
uuid = "e4421f97-9838-4fd0-9fa5-94f11373bf78"
version = "0.8.0"
authors = ["SÃ©bastien Celles <s.celles@gmail.com>"]

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"

[weakdeps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extensions]
GiacSymbolicsExt = "Symbolics"

[compat]
Aqua = "0.8"
CSV = "0.10"
CxxWrap = "0.16, 0.17"
DataFrames = "1.6, 1.7, 1.8"
Libdl = "1.10"
LinearAlgebra = "1.10"
Symbolics = "5, 6, 7"
Tables = "1.10, 1.11, 1.12"
Test = "1.10"
julia = "1.10"
libcxxwrap_julia_jll = "0.14.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "Symbolics", "DataFrames", "CSV"]
