name = "Giac"
uuid = "e4421f97-9838-4fd0-9fa5-94f11373bf78"
authors = ["SÃ©bastien Celles <s.celles@gmail.com>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[weakdeps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extensions]
GiacSymbolicsExt = "Symbolics"

[compat]
Aqua = "0.8"
CxxWrap = "0.16, 0.17"
LinearAlgebra = "1.10"
Libdl = "1.10"
Symbolics = "5, 6, 7"
Test = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[targets]
test = ["Test", "Aqua", "Symbolics"]
